### ISSUE TITLE
Evaluation lack of context

### ISSUE THREAD

**Issue by vTuanpham** [VinAIResearch/PhoGPT#25]
![image](https://github.com/VinAIResearch/PhoGPT/assets/82665400/2df4b8b9-81c5-4e2c-a617-d418d25aca68)

Is the question suppose to be this lack of context ? Given that only the Ground truth even mention about Vietnam.

**Comment by datquocnguyen** [comment]
I don't quite understand your question.
Please could you elaborate a bit more?

**Comment by vTuanpham** [comment]
Hi @datquocnguyen . what i meant is that the question doesn't explicitly mention Vietnam, so it's reasonable to assume that it pertains to a global context rather than being specific to Vietnam. This is evidenced by the failure of all models to provide satisfactory answers to both questions.

**Comment by datquocnguyen** [comment]
It should be reasonable to assume that the question asks about Vietnam rather than the global context, as it's written in Vietnamese. You can think about other questions such as "vượt đèn đỏ phạt bao nhiêu tiền." If you'd like to ask about the global context, you should specify that in the input prompt.
